services:
  postgres:
    image: postgres
    container_name: exdraw_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exdraw_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
